apiVersion: v1
kind: Service
metadata:
  name: app-web
  labels:
    io.kompose.service: app-web
spec:
  type: {{ .Values.appServer.service.type }}
  selector:
    io.kompose.service: app-web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30218
      protocol: TCP
      name: http
